"""Tests for `generate_version.py`: the one-shot geometry and the refusals before the POST.

Split out of `test_dataset_tools.py` along its section banners; the fixtures this and the
other split modules share live in `tests/dataset_tool_helpers.py`. Nothing here touches the
dataset workspace - the tools read it lazily, from inside `main()`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
import clean_v2
import generate_version
import generations
import label_classes
import label_progress
import plan_split

# Rebuilt from the modules that own each fact, not copied by value.
V2 = generations.V2
REPO_ROOT = Path(__file__).resolve().parents[2]
DOC = REPO_ROOT / "docs" / "MODEL_TRAINING.md"
CHECKLIST = REPO_ROOT / "docs" / "CAPTURE_CHECKLIST.md"


# --------------------------------------------------------------------------
# 4. Version generation: the one-shot geometry settings
# --------------------------------------------------------------------------


def test_the_version_settings_are_v1s_settings():
    """Pinned against the version that actually shipped: `scanncart-grocery/1` records
    exactly this block, and it scored mAP 98.21. Changing any of it is a decision, not a
    tidy-up, so it has to be a deliberate edit here rather than a silent retune."""
    settings = generate_version.version_settings()
    assert settings == {
        "preprocessing": {
            "auto-orient": True,
            "resize": {"width": 640, "height": 640, "format": "Stretch to"},
        },
        "augmentation": {},
    }


def test_sanity_and_the_generator_agree_on_the_geometry():
    """One source of truth. `sanity` judges an existing version against this and
    `generate_version` sends it; two copies could disagree, and the failure would be a
    check that approves a version the generator would never produce."""
    assert clean_v2.EXPECTED_RESIZE == generate_version.EXPECTED_RESIZE
    assert generate_version.EXPECTED_SIZE == clean_v2.EXPECTED_RESIZE[0]


def test_a_matching_version_raises_nothing():
    assert generate_version.compare_preprocessing(generate_version.version_settings()["preprocessing"]) == []


def test_a_letterboxed_version_is_flagged_with_the_arithmetic():
    """The difference this catches is not cosmetic: at 1280x720 the x axis is the binding
    one, so `Fit within` gives back the same 0.5 scale horizontally but drops the vertical
    scale from 0.889 to 0.5 - every object at 1.8x fewer pixels, worst on the far cells."""
    problems = generate_version.compare_preprocessing(
        {"auto-orient": True, "resize": {"width": 640, "height": 640, "format": "Fit within"}}
    )
    assert len(problems) == 1
    assert "Fit within" in problems[0] and "padding" in problems[0]


def test_a_wrong_size_or_missing_auto_orient_is_flagged():
    problems = generate_version.compare_preprocessing(
        {"resize": {"width": 416, "height": 416, "format": "Stretch to"}}
    )
    assert any("auto-orient" in p for p in problems)
    assert sum("width" in p or "height" in p for p in problems) == 2


def test_a_version_with_no_preprocessing_is_reported_not_crashed():
    """A version generated by hand, or by an older tool, is the ordinary case - so this is
    total over its input rather than trusting the response's shape."""
    assert generate_version.compare_preprocessing(None)
    assert generate_version.compare_preprocessing([])
    assert generate_version.compare_preprocessing("Stretch to")


def test_filter_null_is_flagged_as_dropping_the_hard_negatives():
    """The dangerous step, named as such: null annotations ARE the hard-negative set, so
    filtering them removes the background frames the model was meant to learn from - and
    the count afterwards would still look plausible."""
    problems = generate_version.compare_preprocessing(
        {
            "auto-orient": True,
            "resize": {"width": 640, "height": 640, "format": "Stretch to"},
            "filter-null": {"percent": 50},
        }
    )
    assert len(problems) == 1
    assert "hard negatives" in problems[0]


def test_the_next_version_number_counts_a_trashed_version():
    """A trashed version still holds its number, which is why this project's next
    generation is 2 and why the weights are named v2 rather than v1."""
    assert generate_version.next_version({"versions": [{"id": "ws/proj/1"}]}) == 2
    assert generate_version.next_version({"versions": [{"id": "ws/proj/1"}, {"id": "ws/proj/3"}]}) == 4
    assert generate_version.next_version({"versions": []}) is None
    assert generate_version.next_version({}) is None


def test_only_class_names_that_carry_a_distance_are_returned():
    """The predicate half, and the false alarm it must never raise: the real roster - and
    `Palmolive` above all - has to come back empty.
    """
    roster = {name: i for i, name in enumerate(label_classes.SLUG_TO_CLASS.values())}
    found = generate_version.classes_with_distance(
        {**roster, "Palmolive Naturals Bar Soap 85g far": 9, "safeguard-mid": 10}
    )

    assert found == {"Palmolive Naturals Bar Soap 85g far": ["far"], "safeguard-mid": ["mid"]}
    assert generate_version.classes_with_distance(roster) == {}
    assert generate_version.classes_with_distance({}) == {}
    assert generate_version.classes_with_distance(None) == {}


class _Resp:
    """Just enough of an httpx response for `generate_version.main`."""

    def __init__(self, status_code=200, body=None):
        self.status_code = status_code
        self._body = {} if body is None else body

    def json(self):
        return self._body


def _annotated(labeled: int = 3, nulls: int = 0, unlabeled: int = 0) -> dict[str, dict]:
    """Project records as the search route returns them, in the three states that matter.

    The state is the *type* of `annotations`, which is the whole trick: a **list** means nobody has
    looked, and a dict with `count: 0` is a null annotation - the hard negatives, a decision.
    """
    records: dict[str, dict] = {}
    for index in range(labeled):
        records[f"labeled_{index}.jpg"] = {
            "name": f"labeled_{index}.jpg",  # the sweep indexes by name, as the API answers
            "annotations": {"count": 1, "classes": {label_classes.SLUG_TO_CLASS["milo"]: 1}},
        }
    for index in range(nulls):
        records[f"null_{index}.jpg"] = {
            "name": f"null_{index}.jpg",
            "annotations": {"count": 0, "classes": {}},
        }
    for index in range(unlabeled):
        records[f"unlabeled_{index}.jpg"] = {"name": f"unlabeled_{index}.jpg", "annotations": []}
    return records


class _FakeRoboflow:
    """The three routes `--yes` touches: the project read, the annotation search, and the POST."""

    def __init__(self, project_body, records=None, search_body=None):
        self.project_body = project_body
        self.records = records if records is not None else {}
        # An override for the *search* response, so a route that will not answer is testable.
        self.search_body = search_body
        self.posts: list = []

    # `generate_version` calls `httpx.get`/`httpx.post` on the module, while
    # `label_progress.project_states` opens `httpx.Client(...)` - so the double stands in for both
    # by handing back itself as the client.
    def Client(self, **_kwargs):  # noqa: N802 - named after the httpx API it replaces
        return self

    def __enter__(self):
        return self

    def __exit__(self, *_exc):
        return False

    def get(self, url, **_kwargs):
        return _Resp(200, self.project_body)

    def post(self, url, **kwargs):
        if "/search" in url:
            if self.search_body is not None:
                return _Resp(200, self.search_body)
            return _Resp(200, {"results": list(self.records.values()), "total": len(self.records)})
        self.posts.append(kwargs.get("json"))
        return _Resp(200, {"version": 2, "message": "building"})


def _generator(monkeypatch, classes: dict, records=None, search_body=None) -> _FakeRoboflow:
    fake = _FakeRoboflow(
        {"project": {"classes": classes}, "versions": [{"id": "ws/proj/1"}]},
        _annotated() if records is None else records,
        search_body,
    )
    monkeypatch.setattr(generate_version, "load_key", lambda _project: "k")
    monkeypatch.setattr(generate_version, "httpx", fake)
    # The preflight's image count reads the project through `label_progress`, which owns the
    # three-state rule - so the same fake has to stand in for that module's httpx too.
    monkeypatch.setattr(label_progress, "httpx", fake)
    return fake


def test_the_generator_refuses_a_class_list_with_a_distance_in_it(monkeypatch, capsys):
    """The whole point of the preflight: a version generated from a distance-split class list
    trains one head output per product-and-distance, and a version number cannot be reused -
    so this refuses and spends nothing.
    """
    fake = _generator(
        monkeypatch,
        {
            "Palmolive Naturals Bar Soap 85g close": 1,
            "Palmolive Naturals Bar Soap 85g mid": 2,
            "Palmolive Naturals Bar Soap 85g far": 3,
            "Milo Chocolate Drink 22g Sachet": 4,
        },
    )

    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 2
    # Nothing was sent, so nothing was spent - that is the difference between a refusal and
    # a warning printed after the fact.
    assert fake.posts == []
    out = capsys.readouterr().out
    assert "refusing to generate" in out
    assert "'Palmolive Naturals Bar Soap 85g mid'" in out
    assert "MOVE" in out and "no version number was spent" in out


def test_the_generator_still_generates_a_clean_class_list(monkeypatch, capsys):
    """The other half: a guard that also blocks the correct class list would be worse than
    none, so the roster has to go through untouched - same body as ever.
    """
    roster = {name: i for i, name in enumerate(label_classes.SLUG_TO_CLASS.values())}
    fake = _generator(monkeypatch, roster)

    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 0
    assert fake.posts == [generate_version.version_settings()]
    out = capsys.readouterr().out
    assert "generating version 2" in out
    # The order it checked, said in as many words - a clean check that printed nothing would be
    # indistinguishable from one that never ran.
    assert "  classes  : 7, in v2's order" in out


def test_the_preflight_prints_what_a_version_would_bake_in(monkeypatch, capsys):
    """The one-shot decision, in one read and before it is spent: the class list *in order* (the
    export's indices), the geometry being sent, and how many of the project's images carry a
    decision - which is what the version will contain, because only annotated images enter one.

    A set that is not finished is a **warning** and not a gate: a partial version is a legitimate
    intermediate (and how the set comes back if the labels have to be redone on the server), so what
    it needs is the number in front of the operator, not a refusal.
    """
    roster = {name: i for i, name in enumerate(label_classes.SLUG_TO_CLASS.values())}
    fake = _generator(monkeypatch, roster, _annotated(2, nulls=1, unlabeled=1))

    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 0
    out = capsys.readouterr().out

    assert "project snc-grocery" in out
    assert "  classes  : 7, in v2's order" in out
    assert "   1  " + generations.V2.classes[0] in out  # numbered, so the order is readable
    assert "  settings : auto-orient: True" in out and "Stretch to 640x640" in out
    assert "  images   : 4 in the project - 2 labeled, 1 marked null, 1 not looked at yet" in out
    assert "  entering : 3 frame(s)" in out
    assert "  version  : this generation will be 2" in out
    assert "[!] 1 frame(s) have no decision yet" in out
    # Warned, not blocked - and the null is counted as a decision, which is the whole reason the
    # count is read through `state_of` rather than from a truthiness test on `annotations`.
    assert fake.posts == [generate_version.version_settings()]


def test_check_prints_the_same_readout_and_spends_nothing(monkeypatch, capsys):
    """Why this mode exists: the readout is only useful *before* the number is spent, and `--yes`
    cannot be run to see it. `--check` reads the project, prints the same block, and stops - one
    code path, so what a review shows cannot differ from what the generation sends."""
    roster = {name: i for i, name in enumerate(label_classes.SLUG_TO_CLASS.values())}
    fake = _generator(monkeypatch, roster, _annotated(2, nulls=1, unlabeled=1))

    assert generate_version.main(["--check", "--project", "snc-grocery"]) == 0
    assert fake.posts == []  # the whole point: reviewed, not spent
    out = capsys.readouterr().out
    assert "  classes  : 7, in v2's order" in out
    assert "  entering : 3 frame(s)" in out
    assert "  version  : this generation will be 2" in out
    assert "Nothing was generated (--check)" in out
    assert "generating version" not in out

    # The refusals are the same ones, under --check too: reading the project is what makes them
    # possible, and a review that skipped them would endorse a list the generation would refuse.
    fake = _generator(
        monkeypatch,
        {name: i for i, name in enumerate(generations.V1.classes)},
    )
    assert generate_version.main(["--check", "--project", "snc-grocery"]) == 2
    assert fake.posts == []
    assert "in the wrong order" in capsys.readouterr().out


def test_a_list_that_is_not_the_rosters_is_reported_with_both_differences(monkeypatch, capsys):
    """What the live project actually looks like, and the reason this is a *report* rather than a
    third refusal: `snc-grocery` still holds Palmolive (dropped from the roster) in neither
    generation's order, so a version of it would bake an eighth output the app cannot name. The fix
    is the Classes tab plus `label_classes.py`, which is what owns the membership verdict - but it
    has to be *visible*, or the readout would call that list a pass.
    """
    live = [
        "555 sardines 155grams",
        "Palmolive Naturals Bar Soap 85g",
        "Milo Chocolate Drink 22g Sachet",
        "Bear Brand Fortified Powdered Milk 33g",
        "century_tuna_flakes_in_oil_155_grams",
        "safeguard_pure_white_60g",
        "lucky_me_pancit_canton_calamansi_flavor",
        "silver_swan_sukang_puti_200ML",
    ]
    fake = _generator(monkeypatch, {name: i for i, name in enumerate(live)})

    assert generate_version.main(["--check", "--project", "snc-grocery"]) == 0
    assert fake.posts == []
    out = capsys.readouterr().out
    assert "  classes  : 8 - v2 declares 7 (1 extra, 0 missing)" in out
    assert "  extra    : Palmolive Naturals Bar Soap 85g" in out
    assert "  order    :" not in out  # the order row is only for the unreadable cases
    assert "[!] this is not v2's list" in out


def test_a_project_with_nothing_annotated_is_refused(monkeypatch, capsys):
    """The one emptiness that is never a legitimate intermediate: a version generated from nothing
    freezes an empty set, spends a number that cannot be reused, and reads afterwards as a set that
    is simply small. Refused, before the POST."""
    roster = {name: i for i, name in enumerate(label_classes.SLUG_TO_CLASS.values())}
    fake = _generator(monkeypatch, roster, _annotated(0, unlabeled=3))

    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 2
    assert fake.posts == []
    out = capsys.readouterr().out
    assert "  entering : 0 frame(s)" in out
    assert "freeze an empty set" in out and "no version number was spent" in out


def test_an_index_that_will_not_answer_is_a_note_not_a_dead_run(monkeypatch, capsys):
    """The count is a readout, so the search route failing must not block a generation the two
    class-list refusals were happy with - and it must not read as a clean zero either. Said, and
    then the POST goes ahead."""
    roster = {name: i for i, name in enumerate(label_classes.SLUG_TO_CLASS.values())}
    fake = _generator(monkeypatch, roster, search_body={"error": "index warming up"})

    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 0
    out = capsys.readouterr().out
    assert "  images   : not counted (search failed:" in out and "index warming up" in out
    assert "entering" not in out and "freeze an empty set" not in out
    assert fake.posts == [generate_version.version_settings()]


def test_the_three_annotation_states_are_read_by_type(monkeypatch):
    """`project_states`, which the preflight imports rather than reading `annotations` itself: a
    **list** means nobody has looked, a dict with `count: 0` is a deliberate null (the hard
    negatives), and a dict with boxes is a label. The same rule `label_progress` prints, so the
    panel and the preflight cannot disagree about the same project."""
    fake = _FakeRoboflow({"project": {"classes": {}}}, _annotated(2, nulls=1, unlabeled=1))
    monkeypatch.setattr(label_progress, "httpx", fake)

    assert label_progress.project_states("snc-grocery", "k") == {
        "images": 4,
        "labeled": 2,
        "null": 1,
        "unlabeled": 1,
    }


def test_the_generator_refuses_the_rosters_names_in_another_order(monkeypatch, capsys):
    """The version's export declares the project's class order, so the same seven names in another
    order bake a head whose indices mean a different product than the roster says - and the only
    checks downstream compare names by *membership*, so the first thing that refuses such a set is
    the dataset doctor, on an export that already exists. That is one version number too late: a
    version number cannot be reused, so the refusal has to happen here, before the POST.

    The *set* is deliberately excluded from this check (a missing or extra name is
    `label_classes.py`'s finding), which is asserted in the same test so the two cannot merge into
    one wide "class list is wrong" refusal.
    """
    v1_order = {name: i for i, name in enumerate(generations.V1.classes)}
    fake = _generator(monkeypatch, v1_order)

    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 2
    assert fake.posts == []
    out = capsys.readouterr().out
    assert "refusing to generate" in out and "in the wrong order" in out
    # Both lists, in order, so the fix is a drag on the Classes tab rather than a diff:
    assert "  declared : " + ", ".join(generations.V1.classes) in out
    assert "  expected : " + ", ".join(generations.V2.classes) + "   (v2's order" in out
    assert "Settings -> Classes" in out and "no version number was spent" in out
    # Not the other preflight's message: a wrong order is not a distance.
    assert "carry a distance" not in out

    # A class list that is the *wrong set* is left to `label_classes.py`: this check must not
    # start refusing sets for a reason it cannot name the fix for.
    fake = _generator(monkeypatch, {"Bear Brand Fortified Powdered Milk 33g": 0})
    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 0
    assert fake.posts, "a membership mismatch is not this check's business"


def test_a_project_no_generation_names_is_not_judged_against_one(monkeypatch, capsys):
    """The other way a guard like this goes wrong: judging a project this app has no spec for
    against a roster picked for it. `generations.py` is where each project is written down, so the
    project name resolves the roster - and an unknown one is reported as unchecked rather than
    refused or quietly skipped."""
    reversed_roster = {name: i for i, name in enumerate(reversed(list(label_classes.SLUG_TO_CLASS.values())))}
    fake = _generator(monkeypatch, reversed_roster)

    assert generate_version.main(["--yes", "--project", "some-other-project"]) == 0
    assert fake.posts == [generate_version.version_settings()]
    out = capsys.readouterr().out
    assert "no generation in generations.py uses" in out
    assert "refusing to generate" not in out

    # An empty project is not a pass either: there is nothing to order, and that state belongs to
    # `label_classes.py` - printing "0 classes, in v2's order" here would read as one.
    fake = _generator(monkeypatch, {})
    assert generate_version.main(["--yes", "--project", "snc-grocery"]) == 0
    out = capsys.readouterr().out
    assert "  classes  : none declared" in out
    assert "  order    : not checked - there are no classes to order" in out


def test_the_project_class_order_is_read_by_index_not_by_dict_order():
    """The reader half, pure. Roboflow answers `name -> index` on both routes, and the index is
    the position a version's export writes - so a mapping that arrives in another insertion order
    still reads as the project's order, and a shape with no indices to rank reads as *no order*
    rather than as the order it happened to be written in (which is what a wrong refusal would be
    made of).
    """
    names = list(generations.V2.classes)
    shuffled = {name: i for i, name in reversed(list(enumerate(names)))}
    assert generate_version.class_order(shuffled) == names
    assert generate_version.class_order(names) == names  # a list, as some routes answer to lists
    assert generate_version.class_order({"b": 1, "a": 0}) == ["a", "b"]
    assert generate_version.class_order({"a": "0", "b": "1"}) == ["a", "b"]  # string indices rank
    assert generate_version.class_order({}) == []
    assert generate_version.class_order({"a": None}) is None
    assert generate_version.class_order(None) is None

    # And the verdict over it: only the roster's names in another order is this tool's finding.
    assert generate_version.order_mismatch(names, generations.V2) is None
    assert generate_version.order_mismatch(list(generations.V1.classes), generations.V2) == names
    assert generate_version.order_mismatch(names[:-1], generations.V2) is None
    assert generate_version.order_mismatch(names + ["Palmolive Naturals Bar Soap 85g"], generations.V2) is None
    assert generate_version.order_mismatch([], generations.V2) is None


def test_the_generators_project_resolves_to_its_generation():
    """Which roster a project is held to, from the one place that lists the projects - so a project
    renamed in the spec cannot keep being judged against the old generation's names."""
    assert generate_version.declaring_generation("snc-grocery") is generations.V2
    assert generate_version.declaring_generation("scanncart-grocery") is generations.V1
    assert generate_version.declaring_generation("scanncart-grocery-v2") is None


def test_the_version_settings_are_documented_where_a_reader_will_look():
    """Drift guard: the checklist and MODEL_TRAINING both send a reader to the generator
    rather than to the UI, so the file has to exist under the name they use."""
    for doc in (CHECKLIST, DOC):
        text = doc.read_text(encoding="utf-8")
        assert "generate_version.py" in text, f"{doc.name} does not name the generator"


def test_hard_negatives_are_judged_from_the_project_not_the_manifest():
    """The bug this guards, with the real numbers it fired on: the negatives are their own
    set with their own manifest, so this manifest holds none *by design* - and counting it
    reported "staged: 0" while all 50 were uploaded, sending a reader off to re-shoot work
    that was already done. `sanity` needs the network, so the verdict is a pure function."""
    status, title, detail = clean_v2.hard_negative_verdict(on_server=50, staged_here=0)
    assert status == "ok"
    assert title == "hard negatives: 50 in the project"
    assert "expected" in detail and "null annotation" in detail

    # Nothing anywhere: this is a real gap, and the only case that warns.
    status, title, detail = clean_v2.hard_negative_verdict(on_server=0, staged_here=0)
    assert status == "warn"
    assert "none in the project" in detail

    # Staged but not uploaded is the other real gap, and it is not the same action as
    # "shoot them": the frames exist, so the fix is an upload rather than a camera.
    status, _title, _detail = clean_v2.hard_negative_verdict(on_server=0, staged_here=30)
    assert status == "warn"

    # Negatives in this manifest is unusual enough to say so, not to fail on.
    status, title, detail = clean_v2.hard_negative_verdict(on_server=50, staged_here=50)
    assert status == "ok" and "50 staged here" in title and "unusual" in detail


def test_the_holdout_plan_is_documented_in_the_checklist():
    """Drift guard. The Tier C shoot is described in CAPTURE_CHECKLIST.md and executed by
    `--holdout-session`; a reader who follows the document must land on a flag that
    exists, and the session it names must be the one the planner is told to hold out."""
    text = CHECKLIST.read_text(encoding="utf-8")
    assert "--holdout-session" in text
    assert "plan_split.py" in text
    assert re.search(r"--holdout-session\s+s3", text)


